var Graphics = function(xPos, yPos, scale, type){
    this.xPos = xPos;
    this.yPos = yPos;
    this.scale = scale;
    this.type = type;
    REDDD = "rgb(255,0,0)"
    GREEN = "rgb(0,255,0)"
    BLACK = "rgb(0,0,0)"
    WHITE = "rgb(255,255,255)"
    CLEAR = "rgb(255,255,255,0)"
    SANDD = "rgb(194, 178, 128)"
    CYANN = "rgb(0, 255, 255)"
    MOUTH = "rgb(239,192,182)" //Sienna
    
}
Graphics.prototype.getCoordinates = function(){
    var positions = []
    for(var column = 0; column < 16; column++){
        var rowContents = []
        for(var row = 0; row < 16; row++){
            rowContents.push([this.xPos + row * this.scale, this.yPos + column * this.scale])
        }
        positions.push(rowContents);
    }
    return positions;
}
Graphics.prototype.drawRedSquare = function(){
    var colors = [
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
    ]
    return colors;
}
Graphics.prototype.drawWhiteSquare = function(){
    var colors = [
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
    ]
    return colors;
}
Graphics.prototype.drawPlayerHead = function(){
    var colors = [
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR],
        [CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR],
        [CLEAR, BLACK, BLACK, BLACK, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, WHITE, WHITE, SANDD, SANDD, WHITE, WHITE, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, WHITE, CYANN, SANDD, SANDD, WHITE, CYANN, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, MOUTH, SANDD, SANDD, SANDD, SANDD, MOUTH, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, CLEAR, BLACK, SANDD, SANDD, SANDD, MOUTH, MOUTH, MOUTH, MOUTH, SANDD, SANDD, SANDD, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
    ]
    return colors;
}
