var Graphics = function(xPos, yPos, scale, type){
    this.xPos = xPos;
    this.yPos = yPos;
    this.scale = scale;
    this.type = type;
    REDDD = "rgb(195, 50, 50)"
    GREEN = "rgb(0,255,0)"
    DARKG = "rgb(12,89,34)"
    GREE2 = "rgb(79,164,70)"
    GREE3 = "rgb(148,200,63)"
    GREE4 = "rgb(75, 153, 69)"
    BLACK = "rgb(0,0,0)"
    WHITE = "rgb(255,255,255)"
    CLEAR = "rgb(255,255,255,0)"
    SANDD = "rgb(194, 178, 128)"
    CYANN = "rgb(145, 187, 226)"
    MOUTH = "rgb(239,192,182)" //Sienna
    SHIRT = "rgb(100, 255, 100)"
    DARKB = "rgb(69,42,33)"
    SKINN = "rgb(255,202,148)"
    BROWN = "rgb(119,48,18)"
    BROW1 = "rgb(89,51,40)"
    WHIT1 = "rgb(229, 197, 198)"
    OUTLI = "rgb(103, 10, 54)"
    ROSEE = "rgb(223, 113, 114)"
    GRAYY = "rgb(56, 58, 63)"
}
Graphics.prototype.getColors = function(){
    if(this.type == 1){
        return this.drawWhiteSquare();
    } else if(this.type == 2){
        return this.drawUpperPlayerBody();
    } else if(this.type == 3){
        return this.drawLowerPlayerBody();
    } else if(this.type == 4){
        return this.drawLegs();
    } else if(this.type == 5){
        return this.drawGrass();
    }
}
Graphics.prototype.getCoordinates = function(){
    var positions = []
    for(var column = 0; column < 16; column++){
        var rowContents = []
        for(var row = 0; row < 16; row++){
            rowContents.push([this.xPos + row * this.scale, this.yPos + column * this.scale])
        }
        positions.push(rowContents);
    }
    return positions;
}
Graphics.prototype.move = function(dx, dy){
    this.xPos = this.xPos + dx;
    this.yPos = this.yPos + dy;
}
Graphics.prototype.drawUpperPlayerBody = function(){
    var colors = [
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, DARKB, DARKB, DARKB, DARKB, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, DARKB, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, DARKB, DARKB, DARKB, DARKB, SKINN, SKINN, SKINN, DARKB, DARKB, DARKB, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, DARKB, DARKB, SKINN, SKINN, SKINN, SKINN, SKINN, SKINN, DARKB, DARKB, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, DARKB, BLACK, BLACK, BLACK, SKINN, SKINN, BLACK, BLACK, BLACK, DARKB, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, WHIT1, BROW1, SKINN, SKINN, BROW1, WHIT1, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, SKINN, WHITE, BROWN, SKINN, SKINN, BROWN, WHITE, SKINN, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, SKINN, SKINN, SKINN, SKINN, SKINN, SKINN, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, SKINN, SKINN, SKINN, SKINN, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, CYANN, ROSEE, ROSEE, CYANN, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, GRAYY, GRAYY, GRAYY, REDDD, REDDD, GRAYY, GRAYY, GRAYY, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, GRAYY, GRAYY, GRAYY, GRAYY, BLACK, BLACK, GRAYY, GRAYY, GRAYY, GRAYY, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, GRAYY, BLACK, GRAYY, GRAYY, REDDD, REDDD, GRAYY, GRAYY, BLACK, GRAYY, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, GRAYY, BLACK, GRAYY, GRAYY, REDDD, REDDD, GRAYY, GRAYY, BLACK, GRAYY, BLACK, CLEAR, CLEAR],
    ]
    return colors;
}
Graphics.prototype.drawLowerPlayerBody = function(){
    var colors = [
        [CLEAR, CLEAR, BLACK, GRAYY, BLACK, GRAYY, GRAYY, REDDD, REDDD, GRAYY, GRAYY, BLACK, GRAYY, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, GRAYY, BLACK, GRAYY, GRAYY, REDDD, REDDD, GRAYY, GRAYY, BLACK, GRAYY, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, GRAYY, BLACK, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, BLACK, GRAYY, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, SKINN, SKINN, SKINN, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, SKINN, SKINN, SKINN, CLEAR, CLEAR],
        [CLEAR, CLEAR, SKINN, SKINN, SKINN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, SKINN, SKINN, SKINN, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, BLACK, BLACK, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, BLACK, GRAYY, BLACK, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
    ]
    return colors;
}

Graphics.prototype.drawRedSquare = function(){
    var colors = [
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
        [REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD, REDDD],
    ]
    return colors;
}
Graphics.prototype.drawWhiteSquare = function(){
    var colors = [
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
    ]
    return colors;
}
Graphics.prototype.drawPlayerHead = function(){
    var colors = [
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR],
        [CLEAR, CLEAR, BLACK, BLACK, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, WHITE, WHITE, SANDD, SANDD, WHITE, WHITE, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, WHITE, CYANN, SANDD, SANDD, WHITE, CYANN, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, BLACK, SANDD, SANDD, SANDD, MOUTH, SANDD, SANDD, SANDD, SANDD, MOUTH, SANDD, SANDD, SANDD, BLACK, CLEAR],
        [CLEAR, CLEAR, BLACK, SANDD, SANDD, SANDD, MOUTH, MOUTH, MOUTH, MOUTH, SANDD, SANDD, SANDD, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, SANDD, SANDD, SANDD, SANDD, SANDD, SANDD, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR, CLEAR, CLEAR],
    ]
    return colors;
}
Graphics.prototype.drawTorso = function(){
    var colors = [
        [CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR],
        [CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR],
        [BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK],
        [BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK],
        [BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK],
        [BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK],
        [BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK],
        [BLACK, SHIRT, BLACK, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, BLACK, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [BLACK, SHIRT, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SHIRT, BLACK],
        [SANDD, SANDD, CLEAR, BLACK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, BLACK, CLEAR, SANDD, SANDD]
    ]
    return colors;
}
Graphics.prototype.drawLegs = function(){
    var colors = [
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
        [CLEAR, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, BLACK, BLACK, BLACK, BLACK, CLEAR, CLEAR, CLEAR],
    ]
    return colors;
}
Graphics.prototype.drawGrass = function(){
    var colors = [
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE3, GREE2, GREE4, GREE2],
        [GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE4, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE3, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2, GREE2],
        [GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE3, GREE2, GREE3, GREE2],
        [GREE2, GREE2, GREE3, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE4, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
        [GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2, GREE2],
    ]
    return colors;
}